name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller GreenClub-Sensor-Firmware-Uploader.spec &&
                zip -r9 GreenClub-Sensor-Firmware-Uploader.app.zip dist/Green\ Club\ Sensor\ Firmware\ Uploader.app/
            OUT_FILE_NAME: GreenClub-Sensor-Firmware-Uploader-MacOS
            OUT_FILE_PATH: GreenClub-Sensor-Firmware-Uploader.app.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n GreenClub-Sensor-Firmware-Uploader --icon=images/icon.ico esptool-python-gui.py
            OUT_FILE_NAME: GreenClub-Sensor-Firmware-Uploader-Windows
            OUT_FILE_PATH: dist/GreenClub-Sensor-Firmware-Uploader.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.OUT_FILE_NAME}}
        path: ${{matrix.OUT_FILE_PATH}}

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Deploy packages
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Green Club Sensor Firmware Uploader ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Upload Windows bundle to release
      id: upload-release-asset-1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GreenClub-Sensor-Firmware-Uploader-Windows/GreenClub-Sensor-Firmware-Uploader.exe
        asset_name: GreenClub-Sensor-Firmware-Uploader.exe
        asset_content_type: application/octet-stream
    - name: Upload Mac OS bundle to release
      id: upload-release-asset-2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GreenClub-Sensor-Firmware-Uploader-MacOS/GreenClub-Sensor-Firmware-Uploader.app.zip
        asset_name: GreenClub-Sensor-Firmware-Uploader.exe
        asset_content_type: application/octet-stream
